steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--platform', 'linux/amd64',
      '-t', 'gcr.io/$PROJECT_ID/portfolio-website:$COMMIT_SHA',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio-website:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'portfolio-website',
      '--image', 'gcr.io/$PROJECT_ID/portfolio-website:$COMMIT_SHA',
      '--region', 'southamerica-east1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/portfolio-website:$COMMIT_SHA'

# Optional timeout setting (default is 10 minutes)
timeout: '1800s'

# Logging configuration
options:
  logging: CLOUD_LOGGING_ONLY 