# Generated by Django 4.1 on 2022-08-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_tags_alter_project_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
